<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action="../../index.php?c=product&a=save">
		<table border="1" width="50%">
			<tr>
				<td>name</td>
				<td><input type="text" name="name"></input></td>
			</tr>
			<tr>
				<td>sku</td>
				<td><input type="text" name="sku"></input></td>
			</tr>
			<tr>
				<td>cost</td>
				<td><input type="text" name="cost"></input></td>
			</tr>
			<tr>
				<td>price</td>
				<td><input type="text" name="price"></input></td>
			</tr>
			<tr>
				<td>status</td>
				<td>
					<Select name="status">
						<option value="AVAILABLE">AVILABLE</option>
						<option value="INAVAILABLE">INAVAILABLE</option>
					</Select>
				</td>
			</tr>
			<tr>
				<td>Quantity</td>
				<td><input type="text" name="quantity"></input></td>
			</tr>
			<tr>
				<td>discription</td>
				<td><input type="text" name="discription"></input></td>
			</tr>
			<tr>
				<td colspan="2" align="center"><input type="submit"></input></td>
			</tr>
		</table>
	</form>

</body>
</html>