<?php 
$products = $this->products;
$pager = $this->getPager();
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table border="1" width="100%">
		<tr>
			<td><h3>Manage Product</h3></td>
			<td><a href="index.php?c=product&a=add">ADD</a></td>
		</tr>
		<tr>
			<th>product_id</th>
			<th>name</th>
			<th>sku</th>
			<th>cost</th>
			<th>price</th>
			<th>status</th>
			<th>description</th>
			<th>inserted_at</th>
			<th>EDIT</th>
			<th>DELETE</th>
	    </tr>
	    <?php foreach($products as $row): ?>
		<tr>
	    	<td><?php echo $row->product_id; ?></td>
			<td><?php echo $row->name;?></td>
			<td><?php echo $row->sku;?></td>
			<td><?php echo $row->cost;?></td>
			<td><?php echo $row->price;?></td>
			<td><?php echo $row->status;?></td>
			<td><?php echo $row->discription;?></td>
			<td><?php echo $row->inserted_at;?></td>
			<td><a href="index.php?c=product&a=edit&product_id=<?php echo $row->product_id ?>">EDIT</a></td>
			<td><a href="index.php?c=product&a=delete&product_id=<?php echo $row->product_id ?>">DELETE</a></td>

		</tr>
	    <?php endforeach;?>

	</table>
	<table>
	<td>
		<a href="index.php?c=product&a=grid&p=<?php echo $pager->start; ?>">START</a>
	</td>
	<td>
		<a href="index.php?c=product&a=grid&p=<?php echo $pager->previous;?>">PREVIOUS</a>
	</td>
	<td>
		<a href="index.php?c=product&a=grid&p=<?php echo $pager->getCurrentPage();?>"><?php echo $pager->getCurrentPage();?></a>
	</td>
	<td>
		<a href="index.php?c=product&a=grid&p=<?php echo $pager->next;?>">NEXT</a>
	</td>
	<td>
		<a href="index.php?c=product&a=grid&p=<?php echo $pager->end; ?>">END</a>
	</td>
    </table>

</body>
</html>