<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action="../../index.php?c=customer&a=save">
	<table border="1" width="100%">
		<tr>
			<td><h3>Customer Info</h3></td>
		</tr>
		<tr>
			<td>First Name</td>
			<td><input type="text" name="customer[first_name]"></input></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" name="customer[last_name]"></input></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="customer[email]"></input></td>
		</tr>
		<tr>
			<td>Mobile</td>
			<td><input type="text" name="customer[mobile]"></input></td>
		</tr>
		<tr>
			<td>Gender</td>
			<td><input type="text" name="customer[gender]"></input></td>
		</tr>
		<tr>
			<td>status</td>
			<td>
				<select name="customer[status]">
					<option value="AVAILABLE">AVAILABLE</option>
					<option value="INAVAILABLE">INAVAILABLE</option>
				</select>
			</td>
		</tr>
		<tr>
			<td><h3>Address Info</h3></td>
		</tr>
		<tr>
			<td>Address</td>
			<td><input type="text" name="Address[address]"></input></td>
		</tr>
		<tr>
			<td>City</td>
			<td><input type="text" name="Address[city]"></input></td>
		</tr>
		<tr>
			<td>Zipcode</td>
			<td><input type="text" name="Address[zipcode]"></input></td>
		</tr>
		<tr>
			<td>state</td>
			<td><input type="text" name="Address[state]"></input></td>
		</tr>
		<tr>
			<td>Country</td>
			<td><input type="text" name="Address[country]"></input></td>
		</tr>
		<tr>
			<td colspan = "2" align="center"><input type="submit"></input></td>
		</tr>
	</table>
	</form>
</body>
</html>