<?php 
$row = $this->customers;
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table>
		<tr>
			<td><h3>Customer Info</h3></td>
		</tr>
		<tr>
			<td>First Name</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Mobile</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Gender</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Status</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td><h3>Address Info</h3></td>
		</tr>
		<tr>
			<td>Address</td>
			<td><input type="text" value="<?php echo $row->address ?>"></input></td>
		</tr>
		<tr>
			<td>City</td>
			<td><input type="text" value="<?php echo $row->city ?>"></input></td>
		</tr>
		<tr>
			<td>Zipcode</td>
			<td><input type="text" value="<?php echo $row->zipcode ?>"></input></td>
		</tr>
		<tr>
			<td>State</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Country</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>

	</table>
</body>
</html>