<?php 
$row = $this->customers;
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action="index.php?c=customer&a=save&customer_id=<?php echo $row->customer_id ?>">
	<table>
		<tr>
			<td><h3>Customer Info</h3></td>
		</tr>
		<tr>
			<td>First Name</td>
			<td><input type="text" name = "customer[first_name]" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" name = "customer[last_name]" value="<?php echo $row->last_name ?>"></input></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name = "customer[email]" value="<?php echo $row->email ?>"></input></td>
		</tr>
		<tr>
			<td>Mobile</td>
			<td><input type="text" name = "customer[mobile]" value="<?php echo $row->mobile ?>"></input></td>
		</tr>
		<tr>
			<td>Gender</td>
			<td><input type="text" value="<?php echo $row->gender ?>"></input></td>
		</tr>
		<tr>
			<td>Status</td>
			<td><input type="text" value="<?php echo $row->status ?>"></input></td>
		</tr>
		<tr>
			<td><h3>Address Info</h3></td>
		</tr>
		<tr>
			<td>Address</td>
			<td><input type="text" name = "Address[address]" value="<?php echo $row->address ?>"></input></td>
		</tr>
		<tr>
			<td>City</td>
			<td><input type="text" name = "Address[city]" value="<?php echo $row->city ?>"></input></td>
		</tr>
		<tr>
			<td>Zipcode</td>
			<td><input type="text" value="<?php echo $row->zipcode ?>"></input></td>
		</tr>
		<tr>
			<td>State</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td>Country</td>
			<td><input type="text" value="<?php echo $row->first_name ?>"></input></td>
		</tr>
		<tr>
			<td><input type = 'submit'></input></td>
		</tr>
		<form>

	</table>
</body>
</html>