<?php 

$customer = $this->customers;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>

	<table border="1" width="100%">
		<tr>
			<td><h3>CUSTOMER INFO</h3></td>
			<td><h3><a href="view/customer/add.phtml">ADD</a></h3></td>
		</tr>
		<tr>
			<th>customer_id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>E Mail</th>
			<th>Mobile</th>
			<th>Gender</th>
			<th>Status</th>
			<th>Address</th>
			<th>City</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach($customer as $row): ?>
		<tr>
			<td><?php echo $row->customer_id ?></td>
			<td><?php echo $row->first_name ?></td>
			<td><?php echo $row->last_name ?></td>
			<td><?php echo $row->email ?></td>
			<td><?php echo $row->mobile ?></td>
			<td><?php echo $row->gender ?></td>
			<td><?php echo $row->status ?></td>
			<td><?php echo $row->address ?></td>
			<td><?php echo $row->city ?></td>
			<td><a href="index.php?c=customer&a=edit&customer_id=<?php echo $row->customer_id ?>">EDIT</a></td>
			<td><a href="index.php?c=customer&a=delete&customer_id=<?php echo $row->customer_id ?>">DELETE</a></td>
		</tr>
	    <?php endforeach;?>


	</table>
</body>
</html>