<?php 

$row = $this->categorys;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action="../../index.php?c=category&a=grid">
		<table border="1" width="100%">
			<tr>
				<td>name</td>
				<td><input type="text" name="name" value="<?php echo $row->category_id ?>"></input></td>
			</tr>
			<tr>				
				<td>description</td>
				<td><input type="text" name="description" value="<?php echo $row->name ?>"></input></td>
			</tr>
			<tr>
				<td>status</td>
				<td><input type="text" name="status" value="<?php echo $row->status ?>"></input></td>
			<tr>
			<tr>
				<td><input type="submit" ></input></td>
			</tr>
		
		</table>
	</form>
</body>
</html>